version: "3.9"

services:
  # --------------------- PostgreSQL ---------------------------------------
  postgres:
    image: postgres:16-alpine
    container_name: leave_postgres
    ports:
      - "5600:5432"                # host:container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: leave_management
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    networks: [leave_net]

  # --------------------- Node.js Backend ----------------------------------
  backend:
    build: ./Backend               # uses Backend/Dockerfile
    container_name: leave_backend
    ports:
      - "3600:3600"
    depends_on:
      - postgres
    environment:
      PGUSER: postgres
      PGPASSWORD: admin123
      PGHOST: postgres
      PGDATABASE: leave_management
      PGPORT: 5432
    networks: [leave_net]

  # --------------------- Employee Front‑end -------------------------------
  employee-leave:
    build: ./employee-leave
    container_name: employee_leave_ui
    ports:
      - "8600:80"                  # host 8104 → nginx 80
    depends_on:
      - backend
    networks: [leave_net]

  # --------------------- HR Front‑end -------------------------------------
  hr-leave:
    build: ./hr-leave
    container_name: hr_leave_ui
    ports:
      - "8601:80"                  # host 8105 → nginx 80
    depends_on:
      - backend
    networks: [leave_net]

volumes:
  pgdata:

networks:
  leave_net:

